= System architecture

== Context architecture

.System context view
[plantuml]
....
@startuml
!include <C4/C4_Context>

Person(admin, "Admin", "User with administration privileges over the system")
Person(user, "User", "User registered in the system")

System(freehomerp, "FreeHomeRP", "Platform to manage daily household operations")

Rel(admin, freehomerp, "Manages platform settings and users")
Rel(user, freehomerp, "Manages their households finances, inventory, etc.")
@enduml
....

== Container architecture

.System containers view
[plantuml]
....
@startuml
!include <C4/C4_Container>

Person(admin, "Admin", "User with administration privileges over the system")
Person(user, "User", "User registered in the system")

System_Boundary(freehomerp, "FreeHomeRP") {
  Container(webapp, "Web Application")
  ContainerDb(db, "Database")
}

Rel(admin, webapp, "Manages platform settings and users", "HTTPS")
Rel(user, webapp, "Manages their households finances, inventory, etc.", "HTTPS")
Rel(webapp, db, "Reads from/Writes to", "TCP/SQL")
@enduml
....

== Component architecture

=== Web Application Components

.Web Application Components
[plantuml]
....
@startuml
!include <C4/C4_Component>

Person(user, "User", "User registered in the system")

Container_Boundary(webapp, "Web Application") {
  Component(signinpage, "SignInPage")
  Component(signinaction, "SignInServerAction")
  Component(signinusecase, "SignInUseCase")
  Component(sessionservice, "SessionService")
  Component(userrepo, "UserRepository")
  Component(sessionrepo, "SessionRepository")
}
ContainerDb(db, "Database")

Rel(user, signinpage, "Opens sign in page", "HTTPS/GET")
Rel(user, signinaction, "Send their credentials", "HTTPS/POST")
Rel(signinaction, signinusecase, "Uses")
Rel(signinaction, sessionservice, "Uses")
Rel(signinusecase, userrepo, "Uses")
Rel(sessionservice, sessionrepo, "Uses")
Rel(userrepo, db, "Reads from/Writes to", "TCP/SQL")
Rel(sessionrepo, db, "Reads from/Writes to", "TCP/SQL")
@enduml
....
