= System Usecases

.Usecases general view
[plantuml]
....
@startuml
left to right direction

usecase "Sign in using credentials" as SignIn

actor "Admin" as Admin
actor "User" as User

Admin --> SignIn
User --> SignIn

@enduml
....

== Authentication

[#US01/0001]
=== US01/0001: Sign in using credentials

Priority:: Must
Actors:: Admin/User and System
Description:: The user must be able to log in to the system with their username and password.
Preconditions::
    - The user must have access to a device with an internet connection.
    - The user must be registered in the system.
Postconditions::
    - The user is either logged in to the system or has received an error message.
Main Scenario::
    . The user accesses the system's login page.
    . The user enters their username and password in the corresponding fields.
    . The system validates the credentials, sign the user in and redirects it to the main page.
        .. If the credentials are invalid, the system displays an error message to the user and goes back to the first step.
