= System requirements specification

include::partial$overview.adoc[]

== System features

=== Admin console

==== Authentication

The system will provide a mechanism to authenticate the administrators that try to use the admin console. Also the authenticated user should be able to close their session once finished.

[cols="1,2,1,1"]
|===
| Name | Description | Priority | Use Cases

| Sign in
| The system should allow an admin to sign in to admin console using their credentials
| Must
| xref:requirements/usecases.adoc#ADM01/0001[ADM01/0001] +
  xref:requirements/usecases.adoc#ADM01/0002[ADM01/0002]

| Sign out
| The system should allow an admin to sign out from admin console
| Must
| xref:requirements/usecases.adoc#ADM01/0003[ADM01/0003]

|===

== Data requiremens

[plantuml]
....

package Households <<Aggregate>> {
    class Household <<Root>> {
        name: string
    }
}

package Users <<Aggregate>> {
    class User <<Root>> {
        username: string
        password: string
        isAdmin: boolean
    }
}

Users.User }|-|{ Households.Household

....
